### PR TITLE
Small fixes and improvements

### PR DESCRIPTION
**Pull request by nahuhh**
- Fixed $(pidof monerod) on exit
- Added config file
Edit config if you need to change options. 
Located at ~/monero-cli/config/config.txt
- Added: download ban list during install and node update
- Added: instructions for port forwarding and disabling auto ip assignment via DHCP 
- Small changes to uninstall (prompt to delete config file and uninstall file)
- Switch uninstall file from sh to bash, to get rid of the errors in terminal

### CODE REVIEW

**Comment by nahuhh** [comment]
Hey. I introduced some issues here.

Fixed in updated code "rc3"

**Comment by CryptoGrampy** [comment]
Hey @nahuhh-

This looks fantastic!  I think the only concern I have is on the blocklist.  Rather than pulling a file from a repo, why not use the built in `--enable-dns-blocklist` added here: https://github.com/monero-project/monero/pull/7139?  It eliminates the need to pull and deal with a file, and I think most people reading through the code would probably prefer to see a built-in monerod method (with a list url that's hardcoded into monerod). 

Beyond that, it's a holiday week over here in the states, and I won't be home until early next week to test this out.  As soon as I test this out, I'll merge.  In the meantime, perhaps @plowsof could also take a look.  

Other thoughts- how do you and @plowsof  feel about defaulting to a pruned node?

**Comment by nahuhh** [comment]
- [x]  I have no problem removing the blocklist and enabling the dns blocklist in the config.
Will do that now.
- [x]  regarding pruning by default, perhaps we can add a prompt. 
``"Pruned node (64gb minimum, 128+gb rec.)
Full node (128gb minimum, 256+gb rec.)
``

Done. 

I have it set to automatically run full nodes (if user doesn't select pruned). 
The script is too easy too use.. Should help getting a lot of people running nodes on spare devices. Tablets, Android tv, etc
It's better if people run full nodes, but the prompt is there for those who read them.

So, this update includes:
Mostly usability / onboarding upgrades

- Foreground and background launching
- config file
- prompt for pruning (only once, at install) 
- instructions on port forwarding
And more

Happy holidays.

**Comment by plowsof** [comment]
Thanks nahuhh. Happy holidays!  I will report back when im able to try this out. Full nodes are best but the more nodes the better (even if theyre pruned) - prompting for pruned is ideal. 

One other improvement would be to do away with the 'sleeps' and replace them with ' while - node offline - retry for a maximum of 30 seconds - if its still offline after that then - error we have a problem - and if its online after one seconds , great, we saved you time'  easier said than done in bash (i would have to search how to do this but i already see do-while stuff)

**Comment by nahuhh** [comment]
> Thanks nahuhh. Happy holidays!  I will report back when im able to try this out. Full nodes are best but the more nodes the better (even if theyre pruned) - prompting for pruned is ideal. 
> 
> One other improvement would be to do away with the 'sleeps' and replace them with ' while - node offline - retry for a maximum of 30 seconds - if its still offline after that then - error we have a problem - and if its online after one seconds , great, we saved you time'  easier said than done in bash (i would have to search how to do this but i already see do-while stuff)

Hey, 
The prompt is added
I actually just increased the delay to 30 seconds (Via sleep) due to a slower devices taking a long time to load the blockchain (Pruned).
It takes ~10-30 seconds to load the pruned chain in my testing, not sure if 30 seconds is long enough for the full blockchain. 

Feel free to work on the sleeps. I'm ok with how the notification functions in the latest version, though of course it could be done better. 

I've also updated a device which was running cryptogrampy main, without issue. 

Im thinking of looking into 
- SD card detection 
- free space detection 
- skip the prompt and default to pruned if under under 128gb free space
- warn if under 64 gb
- prompt to go full if over 128gb free space
- exit with error if under 44gb

Might not get this done for a few days, but feel free to have a go at it

**Comment by CryptoGrampy** [comment]
@nahuhh @plowsof  Just want to confirm that this worked GREAT on a fresh install.  The pruned vs full prompt is fantastic.  

One thing that might be nice to add is a -y or -n on the Termux package update.  It often asks if you want to use the local or the package maintainers version of a various apps during the install process... would be good to just default this to the 'best' option for people (-n ?) so they don't have to deal with it during the install.

**Comment by CryptoGrampy** [comment]
And good thoughts on the SD card size stuff.  I think the prompt is a good place for displaying that data- it may be good to always show it, and just disable the full node option if size < 128 GB as it would be good for people to know they're running pruned and that they *could* upgrade their SD card if they want to run full.  Additionally, if their card is sub 44, I also think it's a good idea to show the prompt, disable both options and say "Your card is too small to run.  Please upgrade to a 256 GB card and rerun the installer.  Press Okay to exit"

**Comment by nahuhh** [comment]
> One thing that might be nice to add is a -y or -n on the Termux package update.  It often asks if you want to use the local or the package maintainers version of a various apps during the install process... would be good to just default this to the 'best' option for people (-n ?) so they don't have to deal with it during the install. 

During the initial update, the prompt is to use a different sources.list 
I can't remember the one that is shipped, but the pkg maintainer vs points to termux.org. 

I think the best option here is Y. Though im not sure how to have to automatically select Y.

**Comment by nahuhh** [comment]
https://github.com/nahuhh/android-termux-monero-node/blob/RC5/src/full-monero-node-external-sd-install.sh

I do believe this to be working properly, but needs some testing.

Edit. Might be broken, hold off for now.

Update:
Ok, good to go, or at least test
[Changes]():https://github.com/nahuhh/android-termux-monero-node/commit/7ee8ddecd260caf4ad605c9cb926d7774edf95bf

UPDATE.
Seems to have messed up my internal storage. 
I think I know why I lost data 😓. Not the script, but I ran rm storage/downloads while I was half asleep, thinking it would delete the termux symlink. But it deleted the folder. 

Ran a few more times, haven't had it reoccur. 
Appearsnto be good

Install

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/nahuhh/android-termux-monero-node/RC5/src/full-monero-node-external-sd-install.sh)"
```
Release notes:
SD card detect should work for
- new users
- old users who were using an SD card. 
- ~~Does not work for old users without an SD card~~.  (Not any worse than before, but no improvement there. termux-setup-storage overwrites the prior script created external-1 folder)

 Pruning popup should only appear if
A) an SD card exists 
B) internal storage has enough space for a full node.

If not, it will default to pruned.

**Pull request merged**
